
import React, { useState, useEffect } from 'react';
import { fetchSportsData } from '../services/geminiService';

const Betting: React.FC = () => {
  const [oddsData, setOddsData] = useState('Aggregating global market data...');
  const [isRefreshing, setIsRefreshing] = useState(false);

  useEffect(() => {
    loadOdds();
  }, []);

  const loadOdds = async () => {
    setIsRefreshing(true);
    try {
      const data = await fetchSportsData('ODDS', 'European Top 5 Leagues');
      setOddsData(data);
    } catch (e) {
      setOddsData('Market connection lost.');
    } finally {
      setIsRefreshing(false);
    }
  };

  return (
    <div className="container-fluid py-4">
      <div className="d-flex justify-content-between align-items-end mb-5">
        <div>
          <h1 className="display-4 font-condensed fw-black italic text-white mb-2">BETTING INTELLIGENCE</h1>
          <p className="text-electric-red font-condensed tracking-widest fw-black">AI-POWERED MARKET PREDICTIONS & ODDS</p>
        </div>
        <button onClick={loadOdds} className="btn btn-outline-danger rounded-0 font-condensed fw-black tracking-widest px-4 py-2">
          {isRefreshing ? 'REFRESHING...' : 'FORCE REFRESH'}
        </button>
      </div>

      <div className="row g-4">
        <div className="col-lg-8">
          <div className="bg-[#0a0e17] p-5 rounded-4 border border-white border-opacity-10 shadow-inner min-vh-75">
            {isRefreshing ? (
              <div className="d-flex flex-column align-items-center justify-content-center h-100 py-5">
                <div className="spinner-border text-danger mb-4" role="status"></div>
                <p className="font-condensed text-white-50 italic">CRUNCHING LIVE DATA...</p>
              </div>
            ) : (
              <div className="markdown-content text-white opacity-75 fs-5 lh-lg" style={{ whiteSpace: 'pre-wrap' }}>
                {oddsData}
              </div>
            )}
          </div>
        </div>
        
        <div className="col-lg-4">
          <div className="card bg-black border-white border-opacity-5 rounded-4 mb-4">
            <div className="card-body p-4">
              <h3 className="h6 font-condensed fw-black text-electric-red mb-3 tracking-widest">DISCLAIMER</h3>
              <p className="small text-muted mb-0">
                All data provided is generated by AI for informational and entertainment purposes only. The Global Football Watch does not encourage gambling. Please bet responsibly. 18+.
              </p>
            </div>
          </div>

          <div className="card bg-gradient-to-br from-dark to-black border-white border-opacity-10 rounded-4">
             <div className="card-body p-4">
                <h3 className="h5 font-condensed fw-black text-white italic mb-4">SMART ACCUMULATOR PICKS</h3>
                <div className="space-y-3">
                  {[
                    { match: 'Arsenal vs Liverpool', pick: 'BTTS', confidence: '88%' },
                    { match: 'Real Madrid vs Barca', pick: 'Home Win', confidence: '72%' },
                    { match: 'Man City vs Spurs', pick: 'Over 2.5', confidence: '91%' }
                  ].map((pick, i) => (
                    <div key={i} className="p-3 bg-white bg-opacity-5 rounded-3 d-flex justify-content-between align-items-center border-start border-danger border-3 mb-3">
                       <div>
                         <p className="small text-muted fw-bold mb-0 text-uppercase">{pick.match}</p>
                         <p className="text-white fw-black font-condensed mb-0">{pick.pick}</p>
                       </div>
                       <div className="text-end">
                         <span className="badge bg-danger rounded-pill px-3">{pick.confidence}</span>
                       </div>
                    </div>
                  ))}
                </div>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Betting;
